export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const FETCH_COUNTRIES_START = "FETCH_COUNTRIES_START";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAIL = "FETCH_COUNTRIES_FAIL";

export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";

export const VERIFY_CODE_SUCCESS = "VERIFY_CODE_SUCCESS";
export const VERIFY_CODE_FAILED = "VERIFY_CODE_FAILED";

export const FETCH_USER_BY_ID_START = "FETCH_USER_BY_ID_START";
export const FETCH_USER_BY_ID_FAILED = "FETCH_USER_BY_ID_FAILED";
export const FETCH_USER_BY_ID_SUCCESS = "FETCH_USER_BY_ID_SUCCESS";

export const FETCH_BOOK_BY_ID_START = "FETCH_BOOK_BY_ID_START";
export const FETCH_BOOK_BY_ID_FAILED = "FETCH_BOOK_BY_ID_FAILED";
export const FETCH_BOOK_BY_ID_SUCCESS = "FETCH_BOOK_BY_ID_SUCCESS";

export const FETCH_BOOK_USER_BY_ID_START = "FETCH_BOOK_USER_BY_ID_START";
export const FETCH_BOOK_USER_BY_ID_FAILED = "FETCH_BOOK_USER_BY_ID_FAILED";
export const FETCH_BOOK_USER_BY_ID_SUCCESS = "FETCH_BOOK_USER_BY_ID_SUCCESS";

export const ADD_BOOK_START = "ADD_BOOK_START";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAILED = "ADD_BOOK_FAILED";

export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED";

export const ADD_LIKE_SUCCESS = "ADD_LIKE_SUCCESS";
export const ADD_LIKE_FAILED = "ADD_LIKE_FAILED";

export const REMOVE_LIKE_SUCCESS = "REMOVE_LIKE_SUCCESS";
export const REMOVE_LIKE_FAILED = "REMOVE_LIKE_FAILED";

export const ADD_DISLIKE_SUCCESS = "ADD_DISLIKE_SUCCESS";
export const ADD_DISLIKE_FAILED = "ADD_DISLIKE_FAILED";

export const REMOVE_DISLIKE_SUCCESS = "REMOVE_DISLIKE_SUCCESS";
export const REMOVE_DISLIKE_FAILED = "REMOVE_DISLIKE_FAILED";

export const ADD_READLATER_SUCCESS = "ADD_READLATER_SUCCESS";
export const ADD_READLATER_FAILED = "ADD_READLATER_FAILED";

export const REMOVE_READLATER_SUCCESS = "REMOVE_READLATER_SUCCESS";
export const REMOVE_READLATER_FAILED = "REMOVE_READLATER_FAILED";

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD__SUCCESS";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD__SUCCESS";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
